- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: Start nginx
  ansible.builtin.systemd_service:
    state: started
    name: nginx

- name: Copy file
  ansible.builtin.copy:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Remove Default Content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Add directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Extract frontend Content
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/expense-frontend-v2.zip
    dest: /usr/share/nginx/html  
    remote_src: yes

- name: Restart nginx
  ansible.builtin.systemd_service:
    state: restarted
    enabled: yes
    name: nginx 