- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: Start nginx
  ansible.builtin.systemd_service:
    state: started
    name: nginx

- name: Extract frontend Content
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/expense-frontend-v2.zip
    dest: /usr/share/nginx/html  
    remote_src: yes

- name: Restart nginx
  ansible.builtin.systemd_service:
    state: restarted
    enabled: yes
    name: nginx 