- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: Start nginx
  ansible.builtin.systemd_service:
    state: started
    name: nginx

- ansible.builtin.import_role:
  name: app-pre-req

- name: Restart nginx
  ansible.builtin.systemd_service:
    state: restarted
    enabled: yes
    name: nginx 