- name: Install mysql
  ansible.builtin.dnf:
    name: mysql-server
    state: latest

- name: Start MySql service
  ansible.builtin.systemd_service:
    name: mysqld
    enabled: yes
    state: started
    
- name: Setup MySQL Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1