- name: Install mysql
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: Start MySql service
  ansible.builtin.systemd_service:
    name: mysqld
    enabled: yes
    state: started

- name: Install Python MySQL Client
  ansible.builtin.pip:
    name:
      - PyMySQL
      - cryptography
    executable: pip3.9

- name: Setup MySQL Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass "{{mysql_root_password}}"