format_version: 10
pipelines:
  mysql:
    group: defaultGroup
    materials:
      git-da613e5:
        git: https://github.com/saketh-devops-i1/learn-ansible.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      vault_token: AES:5e4SXT3KHQg/8wfgE1XMrg==:+fmxJugTpSOakUjd8BRWTHqoAWH4z0a+4QvSgZP3COc=
    stages:
    - DEV:
        fetch_materials: true
        environment_variables:
          env: dev
        approval:
          type: manual
        jobs:
          ansible-playbook:
            tasks:
            - exec:
                arguments:
                  - ansible.sh
                  - mysql
                command: bash #bash ansible.sh mysql
                run_if: passed
    - QA:
        fetch_materials: true
        environment_variables:
          env: qa
        approval:
          type: manual
        jobs:
          ansible-playbook:
            tasks:
            - exec:
                arguments:
                  - ansible.sh
                  - mysql
                command: bash #bash ansible.sh mysql
                run_if: passed

    - STAGE:
        fetch_materials: true
        environment_variables:
          env: stage
        approval:
          type: manual
        jobs:
          ansible-playbook:
            tasks:
            - exec:
                arguments:
                  - ansible.sh
                  - mysql
                command: bash #bash ansible.sh mysql
                run_if: passed
    - PROD:
        fetch_materials: true
        environment_variables:
          env: prod
        approval:
          type: manual
        jobs:
          ansible-playbook:
            tasks:
            - exec:
                arguments:
                  - ansible.sh
                  - mysql
                command: bash #bash ansible.sh mysql
                run_if: passed