- name: Remove Default Content
  ansible.builtin.file:
    path: "{{ app_loc }}"
    state: absent

- name: Add directory
  ansible.builtin.file:
    path: "{{ app_loc }}"
    state: directory

- name: Extract backend Content
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/expense-{{ component }}-v2.zip
    dest: "{{ app_loc }}" 
    remote_src: yes